services:
  - type: web
    name: telecel-askhr
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        value: telecel-askhr-jwt-secret-2024
      - key: MONGODB_URI
        value: mongodb+srv://askhr_admin:Tettey1234%24%24@cluster0.w8qlyh5.mongodb.net/askhr?retryWrites=true&w=majority
      - key: BREVO_API_KEY
        sync: false
      - key: MAIL_FROM
        value: sir.michaelawukugh@gmail.com
      - key: HR_EMAIL
        value: sir.michaelawukugh@gmail.com
      - key: PORT
        value: 10000
