services:
  - type: web
    name: telecel-askhr
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: HR_EMAIL
        value: sir.michaelawukugh@gmail.com
      - key: PORT
        value: 10000
      - key: MNOTIFY_API_KEY
        sync: false
      - key: MNOTIFY_SENDER_ID
        value: AskHR
      - key: ARKESEL_API_KEY
        sync: false
      - key: ARKESEL_SENDER_ID
        value: AskHR
      - key: HR_PHONE
        sync: false
