services:
  - type: web
    name: telecel-askhr
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        value: mongodb+srv://askhr_admin:Tettey1234%24%24@cluster0.w8qlyh5.mongodb.net/askhr?retryWrites=true&w=majority
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_SECURE
        value: "false"
      - key: SMTP_USER
        value: sir.michaelawukugh@gmail.com
      - key: SMTP_PASS
        value: prti zojv ywoe ttwv
      - key: MAIL_FROM
        value: "Telecel AskHR <sir.michaelawukugh@gmail.com>"
      - key: HR_EMAIL
        value: sir.michaelawukugh@gmail.com
      - key: PORT
        value: 10000
